package com.sav.persistance;

import java.util.HashSet;
import java.util.Set;


// Generated 22 janv. 2015 15:05:41 by Hibernate Tools 3.4.0.CR1

/**
 * Client generated by hbm2java
 */
public class Accessoire implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idaccessoire;
	private String designationAcc;	
	private Set<App_acc> app_accs= new HashSet<App_acc>(0);

	
	public Set<App_acc> getApp_accs() {
		return app_accs;
	}

	public void setApp_accs(Set<App_acc> app_accs) {
		this.app_accs = app_accs;
	}

	public Accessoire() {
	}

	public Accessoire( String designationAcc) {
		
		this.designationAcc = designationAcc;
		
		
	}

	public Integer getIdaccessoire() {
		return idaccessoire;
	}

	public void setIdaccessoire(Integer idaccessoire) {
		this.idaccessoire = idaccessoire;
	}

	public String getDesignationAcc() {
		return designationAcc;
	}

	public void setDesignationAcc(String designationAcc) {
		this.designationAcc = designationAcc;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((designationAcc == null) ? 0 : designationAcc.hashCode());
		result = prime * result
				+ ((idaccessoire == null) ? 0 : idaccessoire.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Accessoire other = (Accessoire) obj;
		if (designationAcc == null) {
			if (other.designationAcc != null)
				return false;
		} else if (!designationAcc.equals(other.designationAcc))
			return false;
		if (idaccessoire == null) {
			if (other.idaccessoire != null)
				return false;
		} else if (!idaccessoire.equals(other.idaccessoire))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Accessoire [idaccessoire=" + idaccessoire + ", designationAcc="
				+ designationAcc + "]";
	}
	



}

	