package com.sav.persistance;

import com.sav.persistance.App_panne;

// Generated 22 janv. 2015 15:05:41 by Hibernate Tools 3.4.0.CR1

/**
 * Client generated by hbm2java
 */
public class App_panne implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idapp_panne;
	private Appel appel;
	private Panne panne;	
	
	public Appel getAppel() {
		return appel;
	}


	public void setAppel(Appel appel) {
		this.appel = appel;
	}


	public Panne getPanne() {
		return panne;
	}


	public void setPanne(Panne panne) {
		this.panne = panne;
	}


	public App_panne() {
	}


	public Integer getIdapp_panne() {
		return idapp_panne;
	}

	public void setIdapp_panne(Integer idapp_panne) {
		this.idapp_panne = idapp_panne;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((idapp_panne == null) ? 0 : idapp_panne.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		App_panne other = (App_panne) obj;
		if (idapp_panne == null) {
			if (other.idapp_panne != null)
				return false;
		} else if (!idapp_panne.equals(other.idapp_panne))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "App_panne [idapp_panne=" + idapp_panne + "]";
	}

	



	}

