package com.sav.persistance;

import com.sav.persistance.App_stat;

// Generated 22 janv. 2015 15:05:41 by Hibernate Tools 3.4.0.CR1

/**
 * Client generated by hbm2java
 */
public class App_stat implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idapp_stat;
	private Appel appel;
	private Statut statut;	
	
	public Appel getAppel() {
		return appel;
	}


	public void setAppel(Appel appel) {
		this.appel = appel;
	}


	public Statut getStatut() {
		return statut;
	}


	public void setStatut(Statut statut) {
		this.statut = statut;
	}


	public App_stat() {
	}


	public Integer getIdapp_stat() {
		return idapp_stat;
	}

	public void setIdapp_stat(Integer idapp_stat) {
		this.idapp_stat = idapp_stat;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((idapp_stat == null) ? 0 : idapp_stat.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		App_stat other = (App_stat) obj;
		if (idapp_stat == null) {
			if (other.idapp_stat != null)
				return false;
		} else if (!idapp_stat.equals(other.idapp_stat))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "App_stat [idapp_stat=" + idapp_stat + "]";
	}

	



	}

