package com.sav.persistance;

import java.util.Date;





// Generated 22 janv. 2015 15:05:41 by Hibernate Tools 3.4.0.CR1

/**
 * Client generated by hbm2java
 */
public class App_fil implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idapp_fil;
	
	private Appel appel;
	private Fil_att fil_att;
	private Date date_affect;
	private Date datePriorite;
	private Integer priorite;
	private boolean diagstiq;
	

	
	public boolean isDiagstiq() {
		return diagstiq;
	}


	public void setDiagstiq(boolean diagstiq) {
		this.diagstiq = diagstiq;
	}


	public Date getDatePriorite() {
		return datePriorite;
	}


	public void setDatePriorite(Date datePriorite) {
		this.datePriorite = datePriorite;
	}


	public Appel getAppel() {
		return appel;
	}


	public void setAppel(Appel appel) {
		this.appel = appel;
	}


	public Integer getIdapp_fil() {
		return idapp_fil;
	}


	public void setIdapp_fil(Integer idapp_fil) {
		this.idapp_fil = idapp_fil;
	}


	public Fil_att getFil_att() {
		return fil_att;
	}


	public void setFil_att(Fil_att fil_att) {
		this.fil_att = fil_att;
	}


	


	public Date getDate_affect() {
		return date_affect;
	}


	public void setDate_affect(Date date_affect) {
		this.date_affect = date_affect;
	}


	public Integer getPriorite() {
		return priorite;
	}


	public void setPriorite(Integer priorite) {
		this.priorite = priorite;
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((datePriorite == null) ? 0 : datePriorite.hashCode());
		result = prime * result
				+ ((date_affect == null) ? 0 : date_affect.hashCode());
		result = prime * result + (diagstiq ? 1231 : 1237);
		result = prime * result
				+ ((idapp_fil == null) ? 0 : idapp_fil.hashCode());
		result = prime * result
				+ ((priorite == null) ? 0 : priorite.hashCode());
		return result;
	}


	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		App_fil other = (App_fil) obj;
		if (datePriorite == null) {
			if (other.datePriorite != null)
				return false;
		} else if (!datePriorite.equals(other.datePriorite))
			return false;
		if (date_affect == null) {
			if (other.date_affect != null)
				return false;
		} else if (!date_affect.equals(other.date_affect))
			return false;
		if (diagstiq != other.diagstiq)
			return false;
		if (idapp_fil == null) {
			if (other.idapp_fil != null)
				return false;
		} else if (!idapp_fil.equals(other.idapp_fil))
			return false;
		if (priorite == null) {
			if (other.priorite != null)
				return false;
		} else if (!priorite.equals(other.priorite))
			return false;
		return true;
	}


	@Override
	public String toString() {
		return "App_fil [idapp_fil=" + idapp_fil + ", date_affect="
				+ date_affect + ", datePriorite=" + datePriorite
				+ ", priorite=" + priorite + ", diagstiq=" + diagstiq + "]";
	}


	
	}

