package com.sav.persistance;



import java.util.Date;
import java.util.HashSet;
import java.util.Set;








import com.sav.persistance.Appel;

// Generated 22 janv. 2015 15:05:41 by Hibernate Tools 3.4.0.CR1

/**
 * Client generated by hbm2java
 */
public class Appel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idappel;

	private String emplacement;
	private Date date_entre;
	private Date date_sortie;
	private String note;
	private String nomclt;
	private Integer idetat;
	private String num_serie;
	private boolean diag;

	private Client client;

	private Machine machine;
	private Etat etat;

	private App_acc app_acc;
	private String designationEtat;

	private Set<App_panne> app_pannes = new HashSet<App_panne>(0);
	private Set<App_stat> app_statuts = new HashSet<App_stat>(0);
	private Set<App_acc> app_accs = new HashSet<App_acc>(0);
	private Set<Info_apl> infos = new HashSet<Info_apl>(0);
	private Set<App_fil> app_fils = new HashSet<App_fil>(0);
	private Set<App_four> app_fours = new HashSet<App_four>(0);
	private Set<Detaille_Etat> det_etat = new HashSet<Detaille_Etat>(0);
	private Set<Diagnostique> diagnostiques= new HashSet<Diagnostique>();

	private String info1;
	private String info2;
	private String info3;
	private String info4;
	private String info5;
	private String info6;
	private String info7;
	private String info8;
	private String info9;
	private String info10;
	private String info11;
	private String info12;

	private Reparation reparation;
	
	
	
	
	
	public Set<Diagnostique> getDiagnostiques() {
		return diagnostiques;
	}

	public void setDiagnostiques(Set<Diagnostique> diagnostiques) {
		this.diagnostiques = diagnostiques;
	}

	public boolean isDiag() {
		return diag;
	}

	public void setDiag(boolean diag) {
		this.diag = diag;
	}

	public Date getDate_sortie() {
		return date_sortie;
	}

	public void setDate_sortie(Date date_sortie) {
		this.date_sortie = date_sortie;
	}

	public Set<Detaille_Etat> getDet_etat() {
		return det_etat;
	}

	public void setDet_etat(Set<Detaille_Etat> det_etat) {
		this.det_etat = det_etat;
	}

	public Set<App_four> getApp_fours() {
		return app_fours;
	}

	public void setApp_fours(Set<App_four> app_fours) {
		this.app_fours = app_fours;
	}

	public Reparation getReparation() {
		return reparation;
	}

	public void setReparation(Reparation reparation) {
		this.reparation = reparation;
	}

	public String getInfo1() {
		return info1;
	}

	public void setInfo1(String info1) {
		this.info1 = info1;
	}

	public String getInfo2() {
		return info2;
	}

	public void setInfo2(String info2) {
		this.info2 = info2;
	}

	public String getInfo3() {
		return info3;
	}

	public void setInfo3(String info3) {
		this.info3 = info3;
	}

	public String getInfo4() {
		return info4;
	}

	public void setInfo4(String info4) {
		this.info4 = info4;
	}

	public String getInfo5() {
		return info5;
	}

	public void setInfo5(String info5) {
		this.info5 = info5;
	}

	public String getInfo6() {
		return info6;
	}

	public void setInfo6(String info6) {
		this.info6 = info6;
	}

	public String getInfo7() {
		return info7;
	}

	public void setInfo7(String info7) {
		this.info7 = info7;
	}

	public String getInfo8() {
		return info8;
	}

	public void setInfo8(String info8) {
		this.info8 = info8;
	}

	public String getInfo9() {
		return info9;
	}

	public void setInfo9(String info9) {
		this.info9 = info9;
	}

	public String getInfo10() {
		return info10;
	}

	public void setInfo10(String info10) {
		this.info10 = info10;
	}

	public String getInfo11() {
		return info11;
	}

	public void setInfo11(String info11) {
		this.info11 = info11;
	}

	public String getInfo12() {
		return info12;
	}

	public void setInfo12(String info12) {
		this.info12 = info12;
	}

	public Set<App_fil> getApp_fils() {
		return app_fils;
	}

	public void setApp_fils(Set<App_fil> app_fils) {
		this.app_fils = app_fils;
	}

	public Set<Info_apl> getInfos() {
		return infos;
	}

	public void setInfos(Set<Info_apl> infos) {
		this.infos = infos;
	}

	public Integer getIdetat() {
		return idetat;
	}

	public void setIdetat(Integer idetat) {
		this.idetat = idetat;
	}

	public String getNote() {
		return note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Set<App_acc> getApp_accs() {
		return app_accs;
	}

	public void setApp_accs(Set<App_acc> app_accs) {
		this.app_accs = app_accs;
	}

	public Set<App_stat> getApp_statuts() {
		return app_statuts;
	}

	public void setApp_statuts(Set<App_stat> app_statuts) {
		this.app_statuts = app_statuts;
	}

	public Set<App_panne> getApp_pannes() {
		return app_pannes;
	}

	public void setApp_pannes(Set<App_panne> app_pannes) {
		this.app_pannes = app_pannes;
	}

	public Etat getEtat() {
		return etat;
	}

	public void setEtat(Etat etat) {
		this.etat = etat;
	}

	public String getDesignationEtat() {
		return designationEtat;
	}

	public void setDesignationEtat(String designationEtat) {
		this.designationEtat = designationEtat;
	}

	public App_acc getApp_acc() {
		return app_acc;
	}

	public void setApp_acc(App_acc app_acc) {
		this.app_acc = app_acc;
	}

	public String getNum_serie() {
		return num_serie;
	}

	public void setNum_serie(String num_serie) {
		this.num_serie = num_serie;
	}

	public Machine getMachine() {
		return machine;
	}

	public void setMachine(Machine machine) {
		this.machine = machine;
	}

	public String getNomclt() {
		return nomclt;
	}

	public void setNomclt(String nomclt) {
		this.nomclt = nomclt;
	}

	public Client getClient() {
		return client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public Appel() {
	}

	public Appel(String emplacement,  Date date_entre,
			String note ,String info1,String info2,String info3,String info4,String info5
			,String info6,String info7,String info8,String info9,String info10,String info11
			,String info12)

	{

		this.emplacement = emplacement;
		
		this.date_entre = date_entre;
		this.note = note;
		this.info1=info1;
		this.info2=info2;
		this.info3=info3;
		this.info4=info4;
		this.info5=info5;
		this.info6=info6;
		this.info7=info7;
		this.info8=info8;
		this.info1=info9;
		this.info1=info10;
		this.info1=info11;
		this.info1=info12;
		
	}

	public Integer getIdappel() {
		return idappel;
	}

	public void setIdappel(Integer idappel) {
		this.idappel = idappel;
	}

	public String getEmplacement() {
		return emplacement;
	}

	public void setEmplacement(String emplacement) {
		this.emplacement = emplacement;
	}


	

	

	

	

	public Date getDate_entre() {
		return date_entre;
	}

	public void setDate_entre(Date date_entre) {
		this.date_entre = date_entre;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((date_entre == null) ? 0 : date_entre.hashCode());
		result = prime * result
				+ ((emplacement == null) ? 0 : emplacement.hashCode());
		result = prime * result + ((idappel == null) ? 0 : idappel.hashCode());
		result = prime * result + ((info1 == null) ? 0 : info1.hashCode());
		result = prime * result + ((info10 == null) ? 0 : info10.hashCode());
		result = prime * result + ((info11 == null) ? 0 : info11.hashCode());
		result = prime * result + ((info12 == null) ? 0 : info12.hashCode());
		result = prime * result + ((info2 == null) ? 0 : info2.hashCode());
		result = prime * result + ((info3 == null) ? 0 : info3.hashCode());
		result = prime * result + ((info4 == null) ? 0 : info4.hashCode());
		result = prime * result + ((info5 == null) ? 0 : info5.hashCode());
		result = prime * result + ((info6 == null) ? 0 : info6.hashCode());
		result = prime * result + ((info7 == null) ? 0 : info7.hashCode());
		result = prime * result + ((info8 == null) ? 0 : info8.hashCode());
		result = prime * result + ((info9 == null) ? 0 : info9.hashCode());
		result = prime * result + ((note == null) ? 0 : note.hashCode());
		
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Appel other = (Appel) obj;
		if (date_entre == null) {
			if (other.date_entre != null)
				return false;
		} else if (!date_entre.equals(other.date_entre))
			return false;
		if (emplacement == null) {
			if (other.emplacement != null)
				return false;
		} else if (!emplacement.equals(other.emplacement))
			return false;
		if (idappel == null) {
			if (other.idappel != null)
				return false;
		} else if (!idappel.equals(other.idappel))
			return false;
		if (info1 == null) {
			if (other.info1 != null)
				return false;
		} else if (!info1.equals(other.info1))
			return false;
		if (info10 == null) {
			if (other.info10 != null)
				return false;
		} else if (!info10.equals(other.info10))
			return false;
		if (info11 == null) {
			if (other.info11 != null)
				return false;
		} else if (!info11.equals(other.info11))
			return false;
		if (info12 == null) {
			if (other.info12 != null)
				return false;
		} else if (!info12.equals(other.info12))
			return false;
		if (info2 == null) {
			if (other.info2 != null)
				return false;
		} else if (!info2.equals(other.info2))
			return false;
		if (info3 == null) {
			if (other.info3 != null)
				return false;
		} else if (!info3.equals(other.info3))
			return false;
		if (info4 == null) {
			if (other.info4 != null)
				return false;
		} else if (!info4.equals(other.info4))
			return false;
		if (info5 == null) {
			if (other.info5 != null)
				return false;
		} else if (!info5.equals(other.info5))
			return false;
		if (info6 == null) {
			if (other.info6 != null)
				return false;
		} else if (!info6.equals(other.info6))
			return false;
		if (info7 == null) {
			if (other.info7 != null)
				return false;
		} else if (!info7.equals(other.info7))
			return false;
		if (info8 == null) {
			if (other.info8 != null)
				return false;
		} else if (!info8.equals(other.info8))
			return false;
		if (info9 == null) {
			if (other.info9 != null)
				return false;
		} else if (!info9.equals(other.info9))
			return false;
		if (note == null) {
			if (other.note != null)
				return false;
		} else if (!note.equals(other.note))
			return false;
		
		return true;
	}

	@Override
	public String toString() {
		return "Appel [idappel=" + idappel + ", emplacement=" + emplacement
				+ ", date_entre=" + date_entre + ", note=" + note + ", info1="
				+ info1 + ", info2=" + info2 + ", info3=" + info3 + ", info4="
				+ info4 + ", info5=" + info5 + ", info6=" + info6 + ", info7="
				+ info7 + ", info8=" + info8 + ", info9=" + info9 + ", info10="
				+ info10 + ", info11=" + info11 + ", info12=" + info12 + "]";
	}

	
	}
