package com.sav.persistance;





// Generated 22 janv. 2015 15:05:41 by Hibernate Tools 3.4.0.CR1

/**
 * Client generated by hbm2java
 */
public class Detaille_Etat implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer iddetaille_etat;
	//private Integer idappel;
	//private Integer idetat;
	// Integer idservice;
	
	
	private Appel appel;
	private Etat etat;
	private Service service;
	private String typeApl;
	
	
	


	public String getTypeApl() {
		return typeApl;
	}
	public void setTypeApl(String typeApl) {
		this.typeApl = typeApl;
	}
	public Appel getAppel() {
		return appel;
	}
	public void setAppel(Appel appel) {
		this.appel = appel;
	}
	public Etat getEtat() {
		return etat;
	}
	public void setEtat(Etat etat) {
		this.etat = etat;
	}
	public Service getService() {
		return service;
	}
	public void setService(Service service) {
		this.service = service;
	}
	public Integer getIddetaille_etat() {
		return iddetaille_etat;
	}
	public void setIddetaille_etat(Integer iddetaille_etat) {
		this.iddetaille_etat = iddetaille_etat;
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((iddetaille_etat == null) ? 0 : iddetaille_etat.hashCode());
		result = prime * result + ((typeApl == null) ? 0 : typeApl.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Detaille_Etat other = (Detaille_Etat) obj;
		if (iddetaille_etat == null) {
			if (other.iddetaille_etat != null)
				return false;
		} else if (!iddetaille_etat.equals(other.iddetaille_etat))
			return false;
		if (typeApl == null) {
			if (other.typeApl != null)
				return false;
		} else if (!typeApl.equals(other.typeApl))
			return false;
		return true;
	}
	@Override
	public String toString() {
		return "Detaille_Etat [iddetaille_etat=" + iddetaille_etat
				+ ", typeApl=" + typeApl + "]";
	}
	
	

	}

