package com.sav.persistance;

import java.util.HashSet;
import java.util.Set;




// Generated 22 janv. 2015 15:05:41 by Hibernate Tools 3.4.0.CR1

/**
 * Client generated by hbm2java
 */
public class Fil_att implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	

	

	private Integer idfil_att;
	private Service service;
	private Set<App_fil> app_fils = new HashSet<App_fil>(0);
	private Integer idservice;
	
	
	
	
	public Integer getIdservice() {
		return idservice;
	}

	public void setIdservice(Integer idservice) {
		this.idservice = idservice;
	}

	public Set<App_fil> getApp_fils() {
		return app_fils;
	}

	public void setApp_fils(Set<App_fil> app_fils) {
		this.app_fils = app_fils;
	}
	
	public Service getService() {
		return service;
	}
	public void setService(Service service) {
		this.service = service;
	}
	public Integer getIdfil_att() {
		return idfil_att;
	}
	public void setIdfil_att(Integer idfil_att) {
		this.idfil_att = idfil_att;
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((idfil_att == null) ? 0 : idfil_att.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Fil_att other = (Fil_att) obj;
		if (idfil_att == null) {
			if (other.idfil_att != null)
				return false;
		} else if (!idfil_att.equals(other.idfil_att))
			return false;
		return true;
	}
	@Override
	public String toString() {
		return "Fil_att [idfil_att=" + idfil_att + "]";
	}
	
	
	
}	