package com.sav.persistance;



// Generated 22 janv. 2015 15:05:41 by Hibernate Tools 3.4.0.CR1

/**
 * Client generated by hbm2java
 */

public class Info_apl implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idinfo_apl;
	private String designationinfo_apl;
	private boolean activation;
	private Appel appel;
	
	
	


	public Appel getAppel() {
		return appel;
	}

	public void setAppel(Appel appel) {
		this.appel = appel;
	}

	public boolean isActivation() {
		return activation;
	}

	public void setActivation(boolean activation) {
		this.activation = activation;
	}

	public Integer getIdinfo_apl() {
		return idinfo_apl;
	}

	public void setIdinfo_apl(Integer idinfo_apl) {
		this.idinfo_apl = idinfo_apl;
	}

	public String getDesignationinfo_apl() {
		return designationinfo_apl;
	}

	public void setDesignationinfo_apl(String designationinfo_apl) {
		this.designationinfo_apl = designationinfo_apl;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (activation ? 1231 : 1237);
		result = prime
				* result
				+ ((designationinfo_apl == null) ? 0 : designationinfo_apl
						.hashCode());
		result = prime * result
				+ ((idinfo_apl == null) ? 0 : idinfo_apl.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Info_apl other = (Info_apl) obj;
		if (activation != other.activation)
			return false;
		if (designationinfo_apl == null) {
			if (other.designationinfo_apl != null)
				return false;
		} else if (!designationinfo_apl.equals(other.designationinfo_apl))
			return false;
		if (idinfo_apl == null) {
			if (other.idinfo_apl != null)
				return false;
		} else if (!idinfo_apl.equals(other.idinfo_apl))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Info_apl [idinfo_apl=" + idinfo_apl + ", designationinfo_apl="
				+ designationinfo_apl + ", activation=" + activation + "]";
	}

}