package com.sav.persistance;

import java.util.HashSet;
import java.util.Set;

// Generated 22 janv. 2015 15:05:41 by Hibernate Tools 3.4.0.CR1

/**
 * Client generated by hbm2java
 */
public class Panne implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idpanne;
	private String designationPan;

	private Set<App_panne> app_pannes= new HashSet<App_panne>(0);
	
	private Set<Diag_panne> diag_pannes = new HashSet<Diag_panne>(0);
	
	private String designationSer;
	private Service service;
	private Set<Appel> appels= new HashSet<Appel>();
	
	
	
	

	public Set<App_panne> getApp_pannes() {
		return app_pannes;
	}
	public String getDesignationSer() {
		return designationSer;
	}

	public void setDesignationSer(String designationSer) {
		this.designationSer = designationSer;
	}

	public Service getService() {
		return service;
	}

	public void setService(Service service) {
		this.service = service;
	}

	public Set<Appel> getAppels() {
		return appels;
	}

	public void setApp_pannes(Set<App_panne> app_pannes) {
		this.app_pannes = app_pannes;
	}

	public Panne() {
	}

	public Panne( String designationPan) {
		
		this.designationPan = designationPan;
		
		
	}

	public Integer getIdpanne() {
		return idpanne;
	}

	public void setIdpanne(Integer idpanne) {
		this.idpanne = idpanne;
	}

	public String getDesignationPan() {
		return designationPan;
	}

	public void setDesignationPan(String designationPan) {
		this.designationPan = designationPan;
	}
	
	

	public Set<Diag_panne> getDiag_pannes() {
		return diag_pannes;
	}
	public void setDiag_pannes(Set<Diag_panne> diag_pannes) {
		this.diag_pannes = diag_pannes;
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((designationPan == null) ? 0 : designationPan.hashCode());
		result = prime * result
				+ ((idpanne == null) ? 0 : idpanne.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Panne other = (Panne) obj;
		if (designationPan == null) {
			if (other.designationPan != null)
				return false;
		} else if (!designationPan.equals(other.designationPan))
			return false;
		if (idpanne == null) {
			if (other.idpanne != null)
				return false;
		} else if (!idpanne.equals(other.idpanne))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Panne [idpanne=" + idpanne + ", designationPan="
				+ designationPan + "]";
	}
	



}

	
