package com.sav.persistance;

import java.util.HashSet;
import java.util.Set;

// Generated 22 janv. 2015 15:05:41 by Hibernate Tools 3.4.0.CR1

/**
 * Client generated by hbm2java
 */
public class Piece implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idpiece;
	private String designationPce;
	private String prixPce;
	
	private Set<Reg_piece> reg_pieces = new HashSet<Reg_piece>(0);
	
	public Set<Reg_piece> getReg_pieces() {
		return reg_pieces;
	}
	public void setReg_pieces(Set<Reg_piece> reg_pieces) {
		this.reg_pieces = reg_pieces;
	}
	
	
	public Piece() {
	}

	public Piece( String designationPce,String prixPce) {
		
		this.designationPce = designationPce;
		this.prixPce = prixPce;
		
		
	}
	
	
	

	public String getDesignationPce() {
		return designationPce;
	}

	public void setDesignationPce(String designationPce) {
		this.designationPce = designationPce;
	}

	

	public String getPrixPce() {
		return prixPce;
	}

	public void setPrixPce(String prixPce) {
		this.prixPce = prixPce;
	}

	public Integer getIdpiece() {
		return idpiece;
	}

	public void setIdpiece(Integer idpiece) {
		this.idpiece = idpiece;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((designationPce == null) ? 0 : designationPce.hashCode());
		result = prime * result + ((idpiece == null) ? 0 : idpiece.hashCode());
		result = prime * result + ((prixPce == null) ? 0 : prixPce.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Piece other = (Piece) obj;
		if (designationPce == null) {
			if (other.designationPce != null)
				return false;
		} else if (!designationPce.equals(other.designationPce))
			return false;
		if (idpiece == null) {
			if (other.idpiece != null)
				return false;
		} else if (!idpiece.equals(other.idpiece))
			return false;
		if (prixPce == null) {
			if (other.prixPce != null)
				return false;
		} else if (!prixPce.equals(other.prixPce))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Piece [idpiece=" + idpiece + ", designationPce="
				+ designationPce + ", prixPce=" + prixPce + "]";
	}

	
	

}