package com.sav.persistance;





// Generated 22 janv. 2015 15:05:41 by Hibernate Tools 3.4.0.CR1

/**
 * Client generated by hbm2java
 */
public class Rep_Utl implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idrep_utl;
	private Utilisateur utilisateur;
	private Reparation reparation;
	
	
	public Reparation getReparation() {
		return reparation;
	}
	public void setReparation(Reparation reparation) {
		this.reparation = reparation;
	}
	public Integer getIdrep_utl() {
		return idrep_utl;
	}
	public void setIdrep_utl(Integer idrep_utl) {
		this.idrep_utl = idrep_utl;
	}
	public Utilisateur getUtilisateur() {
		return utilisateur;
	}
	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((idrep_utl == null) ? 0 : idrep_utl.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Rep_Utl other = (Rep_Utl) obj;
		if (idrep_utl == null) {
			if (other.idrep_utl != null)
				return false;
		} else if (!idrep_utl.equals(other.idrep_utl))
			return false;
		return true;
	}
	@Override
	public String toString() {
		return "Rep_Utl [idrep_utl=" + idrep_utl + "]";
	}


	}

