package com.sav.persistance;

import java.util.HashSet;
import java.util.Set;




// Generated 22 janv. 2015 15:05:41 by Hibernate Tools 3.4.0.CR1

/**
 * Client generated by hbm2java
 */

public class Reparation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idreparation;
	
	private Double totaltache;
	private Double totalpiece;
	private Double totalrep;
	private String datesortie;
	private String observationRep;
	
	private Set<Reg_piece> reg_pieces = new HashSet<Reg_piece>(0);
	private Set<Reg_tache> reg_taches = new HashSet<Reg_tache>(0);
	private Set<Rep_Utl> rep_utls = new HashSet<Rep_Utl>(0);
	private Appel appel;

	
	
	
	
	

	public Set<Rep_Utl> getRep_utls() {
		return rep_utls;
	}

	public void setRep_utls(Set<Rep_Utl> rep_utls) {
		this.rep_utls = rep_utls;
	}
	
	
	public Appel getAppel() {
		return appel;
	}
	public void setAppel(Appel appel) {
		this.appel = appel;
	}
	
	public Set<Reg_tache> getReg_taches() {
		return reg_taches;
	}
	public void setReg_taches(Set<Reg_tache> reg_taches) {
		this.reg_taches = reg_taches;
	}
	public Set<Reg_piece> getReg_pieces() {
		return reg_pieces;
	}
	public void setReg_pieces(Set<Reg_piece> reg_pieces) {
		this.reg_pieces = reg_pieces;
	}
	
	
	public Integer getIdreparation() {
		return idreparation;
	}
	public void setIdreparation(Integer idreparation) {
		this.idreparation = idreparation;
	}
	
	public String getObservationRep() {
		return observationRep;
	}
	public void setObservationRep(String observationRep) {
		this.observationRep = observationRep;
	}
	
	
	public Double getTotaltache() {
		return totaltache;
	}

	public void setTotaltache(Double totaltache) {
		this.totaltache = totaltache;
	}

	public Double getTotalpiece() {
		return totalpiece;
	}

	public void setTotalpiece(Double totalpiece) {
		this.totalpiece = totalpiece;
	}

	public Double getTotalrep() {
		return totalrep;
	}

	public void setTotalrep(Double totalrep) {
		this.totalrep = totalrep;
	}

	public String getDatesortie() {
		return datesortie;
	}
	public void setDatesortie(String datesortie) {
		this.datesortie = datesortie;
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((datesortie == null) ? 0 : datesortie.hashCode());
		result = prime * result
				+ ((idreparation == null) ? 0 : idreparation.hashCode());
		result = prime * result
				+ ((observationRep == null) ? 0 : observationRep.hashCode());
		result = prime * result
				+ ((totalpiece == null) ? 0 : totalpiece.hashCode());
		result = prime * result
				+ ((totalrep == null) ? 0 : totalrep.hashCode());
		result = prime * result
				+ ((totaltache == null) ? 0 : totaltache.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Reparation other = (Reparation) obj;
		if (datesortie == null) {
			if (other.datesortie != null)
				return false;
		} else if (!datesortie.equals(other.datesortie))
			return false;
		if (idreparation == null) {
			if (other.idreparation != null)
				return false;
		} else if (!idreparation.equals(other.idreparation))
			return false;
		if (observationRep == null) {
			if (other.observationRep != null)
				return false;
		} else if (!observationRep.equals(other.observationRep))
			return false;
		
		if (totalpiece == null) {
			if (other.totalpiece != null)
				return false;
		} else if (!totalpiece.equals(other.totalpiece))
			return false;
		if (totalrep == null) {
			if (other.totalrep != null)
				return false;
		} else if (!totalrep.equals(other.totalrep))
			return false;
		if (totaltache == null) {
			if (other.totaltache != null)
				return false;
		} else if (!totaltache.equals(other.totaltache))
			return false;
		return true;
	}
	@Override
	public String toString() {
		return "Reparation [idreparation=" + idreparation 
				+ ", totaltache=" + totaltache + ", totalpiece="
				+ totalpiece + ", totalrep=" + totalrep + ", datesortie="
				+ datesortie + ", observationRep=" + observationRep + "]";
	}
	
	
	
	
	

	}