package com.sav.persistance;



import java.util.HashSet;
import java.util.Set;

import com.sav.persistance.Service;

// Generated 22 janv. 2015 15:05:41 by Hibernate Tools 3.4.0.CR1

/**
 * Client generated by hbm2java
 */
public class Service implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idservice;
	private String designationSer;
	private Set<Panne> pannes= new HashSet<Panne>();
	private Set<Fil_att> fils_att= new HashSet<Fil_att>();
	private Integer idfil_att;
	
	private Set<Utilisateur> utilisateurs= new HashSet<Utilisateur>();
	
	public Set<Utilisateur> getUtilisateurs() {
		return utilisateurs;
	}

	public void setUtilisateurs(Set<Utilisateur> utilisateurs) {
		this.utilisateurs = utilisateurs;
	}
	
	public Integer getIdfil_att() {
		return idfil_att;
	}

	public void setIdfil_att(Integer idfil_att) {
		this.idfil_att = idfil_att;
	}

	public Set<Fil_att> getFils_att() {
		return fils_att;
	}

	public void setFils_att(Set<Fil_att> fils_att) {
		this.fils_att = fils_att;
	}

	public Set<Panne> getPannes() {
		return pannes;
	}

	public void setPannes(Set<Panne> pannes) {
		this.pannes = pannes;                                                     
	}

	public Service() {
	}

	public Service(String designationSer) {

		this.designationSer = designationSer;

	}

	public Integer getIdservice() {
		return idservice;
	}

	public void setIdservice(Integer idservice) {
		this.idservice = idservice;
	}

	
	public String getDesignationSer() {
		return designationSer;
	}

	public void setDesignationSer(String designationSer) {
		this.designationSer = designationSer;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((designationSer == null) ? 0 : designationSer.hashCode());
		result = prime * result
				+ ((idservice == null) ? 0 : idservice.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Service other = (Service) obj;
		if (designationSer == null) {
			if (other.designationSer != null)
				return false;
		} else if (!designationSer.equals(other.designationSer))
			return false;
		if (idservice == null) {
			if (other.idservice != null)
				return false;
		} else if (!idservice.equals(other.idservice))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Service [idservice=" + idservice + ", designationSer="
				+ designationSer + "]";
	}

	
	}


