package com.sav.persistance;

import java.util.HashSet;
import java.util.Set;

// Generated 22 janv. 2015 15:05:41 by Hibernate Tools 3.4.0.CR1

/**
 * Client generated by hbm2java
 */
public class Tache implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idtache;
	private String designationTach;
	private String prixTach;
	private Set<Reg_tache> reg_taches = new HashSet<Reg_tache>(0);
	
	public Set<Reg_tache> getReg_taches() {
		return reg_taches;
	}
	public void setReg_taches(Set<Reg_tache> reg_taches) {
		this.reg_taches = reg_taches;
	}
	
	
	
	public Tache() {
	}

	public Tache( String designationTach,String prixTach) {
		
		this.designationTach = designationTach;
		this.prixTach = prixTach;
		
		
	}
	
	
	

	public String getDesignationTach() {
		return designationTach;
	}

	public void setDesignationTach(String designationTach) {
		this.designationTach = designationTach;
	}

	

	public String getPrixTach() {
		return prixTach;
	}

	public void setPrixTach(String prixTach) {
		this.prixTach = prixTach;
	}

	public Integer getIdtache() {
		return idtache;
	}

	public void setIdtache(Integer idtache) {
		this.idtache = idtache;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((designationTach == null) ? 0 : designationTach.hashCode());
		result = prime * result + ((idtache == null) ? 0 : idtache.hashCode());
		result = prime * result
				+ ((prixTach == null) ? 0 : prixTach.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Tache other = (Tache) obj;
		if (designationTach == null) {
			if (other.designationTach != null)
				return false;
		} else if (!designationTach.equals(other.designationTach))
			return false;
		if (idtache == null) {
			if (other.idtache != null)
				return false;
		} else if (!idtache.equals(other.idtache))
			return false;
		if (prixTach == null) {
			if (other.prixTach != null)
				return false;
		} else if (!prixTach.equals(other.prixTach))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Tache [idtache=" + idtache + ", designationTach="
				+ designationTach + ", prixTach=" + prixTach + "]";
	}

	
	

}